import = ["~/.config/alacritty/themes/coolnight.toml", "~/.config/alacritty/fonts.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "beam"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_title = true
#history = false
#multiplier = false
opacity = 0.90

[window.padding]
x = 15
y = 15

