[font]
size = 10

  [font.normal]
  family = "JetBrainsMono NF SemiBold"

  [font.bold]
  family = "JetBrainsMono NF SemiBold"

  [font.italic]
  family = "JetBrainsMono NF SemiBold"

  [font.bold_italic]
  family = "JetBrainsMono NF SemiBold"

